export const screeningDataItems = [
    {
        id:1,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Pending', 
        hplc: 'Pending',
        cardStatus: 'Handout',
    },
    {
        id:2,
        name: 'Raj Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Submitted',
        hplc: 'Pending',
        cardStatus: 'Pending',
    },
    {
        id:3,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Pending',
        hplc: 'Submitted',
        cardStatus: 'Pending',
    },
    {
        id:4,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Pending',
        resultStatus: 'Pending',
        hplc: 'Pending',
        cardStatus: 'Pending',
    },
    {
        id:5,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Submitted',
        hplc: 'Submitted',
        cardStatus: 'Handout',
    },
    {
        id:6,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Pending',
        resultStatus: 'Submitted',
        hplc: 'Pending',
        cardStatus: 'Pending',
    },
    {
        id:7,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Pending',
        hplc: 'Submitted',
        cardStatus: 'Handout',
    },
    {
        id:8,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Submitted',
        hplc: 'Pending',
        cardStatus: 'Handout',
    },
    {
        id:9,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Pending',
        resultStatus: 'Pending',
        hplc: 'Submitted',
        cardStatus: 'Pending',
    },
    {
        id:10,
        name: 'Sahil Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Submitted',
        resultStatus: 'Pending',
        hplc: 'Submitted',
        cardStatus: 'Pending',
    },
    {
        id:11,
        name: 'Rahul Khan',
        date: '08/10/24',
        centerCode: 'center Code',
        bloodStatus: 'Pending',
        resultStatus: 'Submitted',
        hplc: 'Pending',
        cardStatus: 'Handout',
    },
]


  // Sample Data (Replace with API call) for EditResult
    export const initialData = Array.from({ length: 10 }, (_, index) => ({
        id: index + 1,
        name: "Sahil Khan",
        maritalStatus: "",
        centerCode: "",
        age: "",
        gender: "",
        category: "",
        caste: "",
        location: "",
        bloodStatus: "Submitted", // Default to Submitted
        resultStatus: "Pending",   // Default to Pending
        cardStatus: "Handout", 
    }));